### ISSUE TITLE
Crashes on F030 Nucleo board

### ISSUE THREAD

**Issue by Arjun765** [ARMmbed/mbed-os-example-blinky-baremetal#65]
### Description of defect

It crashes when running on F030 board

>++ MbedOS Error Info ++
>Error Status: 0x80FF0144 Code: 324 Module: 255
>Error Message: Assertion failed: "OS timer not available - check MBED_CONF_TARGET_TICKLESS_FROM_US_TICKER" && >false
>Location: 0x8000DFB
>File: ../mbed-os/platform/source/mbed_os_timer.cpp+55
>Error Value: 0x0

#### Target(s) affected by this defect ?

Nucleo F030
#### Toolchain(s) (name and version) displaying this defect ?
GCC

#### What version of Mbed-os are you using (tag or sha) ?

mbed-os-5.15.3-rc1

**Comment by 0xc0170** [comment]
https://github.com/ARMmbed/mbed-os/blob/mbed-os-5.15/platform/source/mbed_os_timer.cpp#L50 - this is the line that should be true. Can you enable `MBED_CONF_TARGET_TICKLESS_FROM_US_TICKER` by defining tickless from us ticker?

Something like this:
```
	"overrides": {
            "tickless-from-us-ticker": true
        }
```
or just define a macro and set to 1

**Comment by Arjun765** [comment]
Yes, enabling `target.tickless-from-us-ticker` is how i got it to run. Shouldn't it be enabled by default on the F030?

**Comment by jeromecoutant** [comment]
Hi
This was corrected in https://github.com/ARMmbed/mbed-os/pull/12988
Regards,
