### ISSUE TITLE
Example compile by mbed for cmsis-nn 

### ISSUE THREAD

**Issue by ccu1tn** [ARMmbed/mbed-os-example-blinky-baremetal#7]
Dear everyone;

I am looking find an example compile cmsis-nn by mbed. Can everyone share for me a little or tutorial me to do it? 

Many thanks

**Comment by 0xc0170** [comment]
Hi, @ccu1tn please ask this question on the forums in https://developer.mbed.org. You should be able to get an answer. I'll close this question here.
